name: ana_vodafone_lite
description: simple simulation app to ana vodafone app in store
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  custom_navigation_bar:
  connectivity_plus:
  webview_flutter:
  dotted_line:
  google_maps_flutter:
  geolocator:
  path_provider:
  splashscreen:
  animated_bottom_navigation_bar:
  flutter_native_splash:
  loader_overlay:
  flutter_slot_machine:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash:
  flutter_fortune_wheel:

flutter_native_splash:
  color: "#ff0000"
  image: assets/images/logos/vodafone_logo.png
flutter:

  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/backgrounds/
    - assets/images/logos/
    - assets/images/splash/
    - assets/images/banners/
    - assets/webpages/captcha.html

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #         weight: 700